server {
    listen 80;
    server_name site www.site;

    client_max_body_size 50M;

    # Static and media served directly from host paths
    location /static/ {
        alias /srv/portfolio.kg/staticfiles/;
    }
    location /media/ {
        alias /srv/portfolio.kg/media/;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
